version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - bidding-network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - bidding-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bidding_platform
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - bidding-network

networks:
  bidding-network:
    driver: bridge

volumes:
  mysql_data:
